version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - cargo build --release

  objdump:
    cmds:
      - cargo objdump --release -- --disassemble --no-show-raw-insn

  readelf:
    cmds:
      - cargo size --release

  objcopy:
    cmds:
      - rust-objcopy --strip-all -O binary target/aarch64-unknown-none/release/kernel target/aarch64-unknown-none/release/kernel8.img

  qemu:
    cmds:
      - task: build
      - task: objcopy
      - qemu-system-aarch64 -M raspi4b -serial stdio -display none -kernel target/aarch64-unknown-none/release/kernel8.img
    
  qemu-docker:
    cmds:
      - task: build
      - task: objcopy
      - docker run -t --rm -v .:/work/tutorial -w /work/tutorial -i u007d/osdev-utils-rpi4:2023.09 qemu-system-aarch64 -M raspi4 -serial stdio -display none -kernel target/aarch64-unknown-none/release/kernel8.img

  miniterm:
    cmds:
    - task: build
    - task: objcopy
    - docker run -t --rm -v ./work/tutorial -w /work/tutorial -i --privileged -v /dev:/dev -v ./common:/work/common u007d/osdev-utils-rpi4:2023.09 ruby ../common/serial/miniterm.rb /dev/ttyUSB0

  chainboot:
    cmds:
    - task: build
    - task: objcopy
    - docker run -t --rm -v .:/work/tutorial -w /work/tutorial -i --privileged -v /dev:/dev -v ./common:/work/common u007d/osdev-utils-rpi4:2023.09 ruby ../common/serial/minipush.rb /dev/ttyUSB0 demo_payload_rpi4.img
