version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - cargo build --release

  objdump:
    cmds:
      - cargo objdump --release -- --disassemble --no-show-raw-insn

  readelf:
    cmds:
      - cargo size --release

  objcopy:
    cmds:
      - rust-objcopy -O binary target/aarch64-unknown-none/{{.BUILD_TYPE}}/kernel target/aarch64-unknown-none/{{.BUILD_TYPE}}/kernel8.img
    requires:
      vars: [BUILD_TYPE]
  
  qemu:
    cmds:
      - task: build
        vars: 
          BUILD_TYPE: release
      - task: objcopy
        vars: 
          BUILD_TYPE: release
      - qemu-system-aarch64 -M raspi4b -serial stdio -display none -kernel target/aarch64-unknown-none/{{.BUILD_TYPE}}/kernel8.img
    vars:
      BUILD_TYPE: release

  qemu-gdb:
    cmds:
      - cargo build --profile=release-with-debug
      - task: objcopy
        vars: 
          BUILD_TYPE: release-with-debug
      - qemu-system-aarch64 -s -S -M raspi4b -serial stdio -display none -kernel target/aarch64-unknown-none/{{.BUILD_TYPE}}/kernel8.img
    vars:
      BUILD_TYPE: release-with-debug

  gdb-docker:
    cmds:
      - docker run -t --rm -v .:/work/tutorial -w /work/tutorial -i --network host u007d/osdev-utils-rpi4:2023.09 gdb-multiarch -q target/aarch64-unknown-none/debug/kernel
    
  qemu-docker:
    cmds:
      - task: build
        vars: 
          BUILD_TYPE: release
      - task: objcopy
        vars: 
          BUILD_TYPE: release
      - docker run -t --rm -v .:/work/tutorial -w /work/tutorial -i u007d/osdev-utils-rpi4:2023.09 qemu-system-aarch64 -M raspi4 -serial stdio -display none -kernel target/aarch64-unknown-none/{{.BUILD_TYPE}}}/kernel8.img
    vars:
      build_type: release

  miniterm:
    cmds:
    - task: build
    - task: objcopy
    - docker run -t --rm -v ./work/tutorial -w /work/tutorial -i --privileged -v /dev:/dev -v ./common:/work/common u007d/osdev-utils-rpi4:2023.09 ruby ../common/serial/miniterm.rb /dev/ttyUSB0

  chainboot:
    cmds:
    - task: build
      vars: 
          BUILD_TYPE: release
    - task: objcopy
      vars: 
        BUILD_TYPE: release
    - docker run -t --rm -v .:/work/tutorial -w /work/tutorial -i --privileged -v /dev:/dev -v ./common:/work/common u007d/osdev-utils-rpi4:2023.09 ruby ../common/serial/minipush.rb /dev/ttyUSB0 demo_payload_rpi4.img
